[package]
name = "rubik-solver"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rubik-core = { path = "../rubik-core" }
rubik-nxn-solver = { path = "../rubik-nxn-solver" }
rcube-rs = { path = "../rcube-rs" }
serde.workspace = true
serde_json.workspace = true
lazy_static = "1"

[[bin]]
name = "generate_2x2_pdbs"
path = "src/bin/generate_2x2_pdbs.rs"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
wasm-bindgen.workspace = true
