[workspace]
members = ["crates/rubik-app", "crates/rubik-core", "crates/solver-worker"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
bevy = { version = "0.18.1", default-features = false, features = [
  "async_executor",
  "bevy_asset",
  "bevy_camera",
  "bevy_color",
  "bevy_core_pipeline",
  "bevy_image",
  "bevy_input_focus",
  "bevy_light",
  "bevy_log",
  "bevy_mesh",
  "bevy_pbr",
  "bevy_render",
  "bevy_shader",
  "bevy_window",
  "bevy_winit",
  "debug",
  "png",
  "reflect_auto_register",
  "std",
  "touch",
  "webgl2",
] }
console_error_panic_hook = "0.1.7"
js-sys = "0.3.82"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
wasm-bindgen = "0.2.105"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
